[theme]
name = "Leisure 101"
version = "1.0.0"
api_version = "1"
description = "A leisure site theme."
author = "Symantic Signals"

[nav_locations]
primary = "Primary Navigation"
footer  = "Footer Links"
